version: '3'

services:
  db:
    image: mariadb
    env_file:
      - db.env
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  nextcloud:
    image: ripples/nextcloud
    build: nextcloud
    links:
      - db
    env_file:
      - db.env
    environment:
      MYSQL_HOST: db
      NEXTCLOUD_ADMIN_USER: ${ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      USER_ID: ${USER_ID}
    volumes:
      - nextcloud:/var/www/html
      - ${DATA_PATH}:/var/www/html/data
      - ${RO_DATA_PATH}:/ro-data:ro
    restart: unless-stopped

  aria2:
    image: ripples/aria2
    build: aria2
    ports:
      - 6800:6800
    environment:
      SECRET: ${RPC_SECRET}
      USER_ID: ${USER_ID}
    volumes:
      - aria2:/conf
      - ${DATA_PATH}/aria2:/data
    restart: unless-stopped

  proxy:
    image: ripples/caddy:dnspod
    build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        - plugins=dnspod
    links:
      - nextcloud
      - aria2
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    environment:
      - DOMAIN=${DOMAIN}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - DNSPOD_API_KEY=${DNSPOD_API_KEY}
      - CADDYPATH=/etc/caddycerts
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - caddycerts:/etc/caddycerts
    command: ["--conf", "/etc/Caddyfile", "--log", "stdout", "-http-port", "${HTTP_PORT}", "-https-port", "${HTTPS_PORT}"]
    restart: unless-stopped

volumes:
  db:
  nextcloud:
  aria2:
  caddycerts:
